const path = require('path');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
const CopyPlugin = require('copy-webpack-plugin');

const ENV = process.env.NODE_ENV || 'development';
const PROD = ENV === 'production';

module.exports = () => {
  const config = {
    mode: PROD ? 'production' : 'development',
    entry: './bin/pn.ts',
    target: 'node',
    output: {
      filename: 'pn.js',
      path: path.resolve(__dirname, 'out')
    },
    resolve: {
      extensions: ['.js', '.ts', '.json', '.node'],
      modules: ['node_modules'],
    },
    module: {
      rules: [
        {
          test: /\.ts$/,
          exclude: [
            path.resolve(__dirname, '**/*spec.ts')
          ],
          use: [
            {
              loader: 'ts-loader',
              options: {
                transpileOnly: true
              }
            }
          ]
        },
        {
          test: /\.node$/,
          use: 'node-loader'
          /**
           * There is an error that is generated by the bundled code
           * and in order to build, the node_modules/pokeusew/pcsclite/lib/pcsclite.js
           * needs to be modified.
           * 
           * https://stackoverflow.com/questions/42878256/importing-pokusew-pcsclite-in-angular2-electron-throws-typeerror
           * 
           * const pcsclite = require('node-loader!./../build/Release/pcsclite.node');
           * 
           * the line above needs to replace the require on line 4 of that file and 
           * the webpack build will work as expected.
           *
           */
        },
        { test: /.*/, loader: 'shebang-loader' }
      ]
    },
    plugins: [
      new CleanWebpackPlugin(),
      new ForkTsCheckerWebpackPlugin(),
      new CopyPlugin([
        {
          from: './node_modules/@pokusew/pcsclite/build/Release/pcsclite.node',
          to: './Release'
        },
        {
          from: 'package.init.json',
          to: './package.json'
        }
      ])
    ]
  }

  if (!PROD) {
    config.devtool = 'source-map'
  }

  return config
}
