const path = require('path');
const os = require('os');
const childProcess = require('child_process');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
const CopyPlugin = require('copy-webpack-plugin');
const ENV = process.env.NODE_ENV || 'development';
const PROD = ENV === 'production';

module.exports = () => {
  const config = {
    mode: PROD ? 'production' : 'development',
    entry: './bin/pn.ts',
    target: 'node',
    output: {
      filename: 'pn.js',
      path: path.resolve(__dirname, 'out')
    },
    resolve: {
      extensions: ['.js', '.ts', '.json', '.node'],
      modules: ['node_modules']
    },
    module: {
      rules: [
        {
          test: /\.ts$/,
          exclude: [path.resolve(__dirname, '**/*spec.ts')],
          use: [
            {
              loader: 'ts-loader',
              options: {
                transpileOnly: true
              }
            }
          ]
        },
        {
          test: /\.node$/,
          loader: 'node-loader'
          /**
           * There is an error that is generated by the bundled code
           * and in order to build, the node_modules/pokeusew/pcsclite/lib/pcsclite.js
           * needs to be modified.
           *
           * https://stackoverflow.com/questions/42878256/importing-pokusew-pcsclite-in-angular2-electron-throws-typeerror
           *
           */
        },
        {
          test: /.*/,
          loader: 'shebang-loader'
        }
      ]
    },
    plugins: [
      new CleanWebpackPlugin(),
      new CopyPlugin([
        {
          from: './node_modules/pcsclite/build/Release/pcsclite.node',
          // copy binding to '${REPO_ROOT}/${OUTPUT_DIR}/Release
          to: './Release'
        },
        {
          from: 'package.init.json',
          // copy package so the `bindings` import can determine REPO_ROOT
          to: './package.json'
        }
      ])
    ]
  };

  if (!PROD) {
    config.devtool = 'source-map';
  }

  if (!os.arch().includes('arm')) {
    config.plugins.push(new ForkTsCheckerWebpackPlugin());
  }

  return config;
};
